import { translation } from "@/helpers";

const t = (message, data) => translation("usercenter." + message, data);

export const getAllRegion = () => [
  //{ code: "AF", name: t("KYC_account_verification.afghanistan") },
  //{ code: "AX", name: "\u00c5land Islands" },
  //{ code: "AL", name: "Albania" },
  //{ code: "DZ", name: "Algeria" },
  //{ code: "AS", name: "American Samoa" },
  //{ code: "AD", name: "Andorra" },
  //{ code: "AO", name: "Angola" },
  //{ code: "AI", name: "Anguilla" },
  //{ code: "AQ", name: "Antarctica" },
  //{ code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: t("KYC_account_verification.argentina") },
  //{ code: "AM", name: "Armenia" },
  //{ code: "AW", name: "Aruba" },
  { code: "AU", name: t("KYC_account_verification.australia") },
  { code: "AT", name: t("KYC_account_verification.austria") },
  //{ code: "AZ", name: "Azerbaijan" },
  //{ code: "BS", name: "Bahamas" },
  //{ code: "BH", name: "Bahrain" },
  //{ code: "BD", name: "Bangladesh" },
  //{ code: "BB", name: "Barbados" },
  //{ code: "BY", name: "Belarus" },
  { code: "BE", name: t("KYC_account_verification.belgium") },
  //{ code: "BZ", name: "Belize" },
  //{ code: "BJ", name: "Benin" },
  //{ code: "BM", name: "Bermuda" },
  //{ code: "BT", name: "Bhutan" },
  //{ code: "BO", name: "Bolivia, Plurinational State of" },
  //{ code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  //{ code: "BA", name: "Bosnia and Herzegovina" },
  //{ code: "BW", name: "Botswana" },
  //{ code: "BV", name: "Bouvet Island" },
  { code: "BR", name: t("KYC_account_verification.brazil") },
  //{ code: "IO", name: "British Indian Ocean Territory" },
  //{ code: "BN", name: "Brunei Darussalam" },
  //{ code: "BG", name: "Bulgaria" },
  //{ code: "BF", name: "Burkina Faso" },
  //{ code: "BI", name: "Burundi" },
  //{ code: "KH", name: "Cambodia" },
  //{ code: "CM", name: "Cameroon" },
  { code: "CA", name: t("KYC_account_verification.canada") },
  //{ code: "CV", name: "Cape Verde" },
  //{ code: "KY", name: "Cayman Islands" },
  //{ code: "CF", name: "Central African Republic" },
  //{ code: "TD", name: "Chad" },
  { code: "CL", name: t("KYC_account_verification.chile") },
  { code: "CN", name: t("KYC_account_verification.china") },
  //{ code: "CX", name: "Christmas Island" },
  //{ code: "CC", name: "Cocos (Keeling) Islands" },
  //{ code: "CO", name: "Colombia" },
  //{ code: "KM", name: "Comoros" },
  //{ code: "CG", name: "Congo" },
  //{ code: "CD", name: "Congo, the Democratic Republic of the" },
  //{ code: "CK", name: "Cook Islands" },
  //{ code: "CR", name: "Costa Rica" },
  //{ code: "CI", name: "C\u00f4te d'Ivoire" },
  { code: "HR", name: t("KYC_account_verification.croatia") },
  //{ code: "CU", name: "Cuba" },
  //{ code: "CW", name: "Cura\u00e7ao" },
  { code: "CY", name: t("KYC_account_verification.cyprus") },
  //{ code: "CZ", name: "Czech Republic" },
  { code: "DK", name: t("KYC_account_verification.denmark") },
  //{ code: "DJ", name: "Djibouti" },
  //{ code: "DM", name: "Dominica" },
  //{ code: "DO", name: "Dominican Republic" },
  //{ code: "EC", name: "Ecuador" },
  { code: "EG", name: t("KYC_account_verification.egypt") },
  //{ code: "SV", name: "El Salvador" },
  //{ code: "GQ", name: "Equatorial Guinea" },
  //{ code: "ER", name: "Eritrea" },
  { code: "EE", name: t("KYC_account_verification.estonia") },
  //{ code: "ET", name: "Ethiopia" },
  //{ code: "FK", name: "Falkland Islands (Malvinas)" },
  //{ code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: t("KYC_account_verification.fiji") },
  { code: "FI", name: t("KYC_account_verification.finland") },
  { code: "FR", name: t("KYC_account_verification.france") },
  //{ code: "GF", name: "French Guiana" },
  //{ code: "PF", name: "French Polynesia" },
  //{ code: "TF", name: "French Southern Territories" },
  //{ code: "GA", name: "Gabon" },
  //{ code: "GM", name: "Gambia" },
  //{ code: "GE", name: "Georgia" },
  { code: "DE", name: t("KYC_account_verification.germany") },
  //{ code: "GH", name: "Ghana" },
  //{ code: "GI", name: "Gibraltar" },
  { code: "GR", name: t("KYC_account_verification.greece") },
  //{ code: "GL", name: "Greenland" },
  //{ code: "GD", name: "Grenada" },
  //{ code: "GP", name: "Guadeloupe" },
  //{ code: "GU", name: "Guam" },
  //{ code: "GT", name: "Guatemala" },
  //{ code: "GG", name: "Guernsey" },
  //{ code: "GN", name: "Guinea" },
  //{ code: "GW", name: "Guinea-Bissau" },
  //{ code: "GY", name: "Guyana" },
  //{ code: "HT", name: "Haiti" },
  //{ code: "HM", name: "Heard Island and McDonald Islands" },
  //{ code: "VA", name: "Holy See (Vatican City State)" },
  //{ code: "HN", name: "Honduras" },
  { code: "HK", name: t("KYC_account_verification.hongkong") },
  { code: "HU", name: t("KYC_account_verification.hungary") },
  { code: "IS", name: t("KYC_account_verification.iceland") },
  { code: "IN", name: t("KYC_account_verification.india") },
  { code: "ID", name: t("KYC_account_verification.indonesia") },
  //{ code: "IR", name: "Iran, Islamic Republic of" },
  //{ code: "IQ", name: "Iraq" },
  { code: "IE", name: t("KYC_account_verification.ireland") },
  //{ code: "IM", name: "Isle of Man" },
  //{ code: "IL", name: "Israel" },
  { code: "IT", name: t("KYC_account_verification.italy") },
  //{ code: "JM", name: "Jamaica" },
  { code: "JP", name: t("KYC_account_verification.japan") },
  //{ code: "JE", name: "Jersey" },
  //{ code: "JO", name: "Jordan" },
  { code: "KZ", name: t("KYC_account_verification.kazakhstan") },
  //{ code: "KE", name: "Kenya" },
  //{ code: "KI", name: "Kiribati" },
  //{ code: "KP", name: "Korea, Democratic People's Republic of" },
  { code: "KR", name: t("KYC_account_verification.korea") },
  //{ code: "KW", name: "Kuwait" },
  //{ code: "KG", name: "Kyrgyzstan" },
  //{ code: "LA", name: "Lao People's Democratic Republic" },
  //{ code: "LV", name: "Latvia" },
  //{ code: "LB", name: "Lebanon" },
  //{ code: "LS", name: "Lesotho" },
  //{ code: "LR", name: "Liberia" },
  //{ code: "LY", name: "Libya" },
  //{ code: "LI", name: "Liechtenstein" },
  //{ code: "LT", name: "Lithuania" },
  { code: "LU", name: t("KYC_account_verification.luxembourg") },
  { code: "MO", name: t("KYC_account_verification.macao") },
  //{ code: "MK", name: "Macedonia, the Former Yugoslav Republic of" },
  //{ code: "MG", name: "Madagascar" },
  //{ code: "MW", name: "Malawi" },
  { code: "MY", name: t("KYC_account_verification.malaysia") },
  //{ code: "MV", name: "Maldives" },
  //{ code: "ML", name: "Mali" },
  { code: "MT", name: t("KYC_account_verification.malta") },
  //{ code: "MH", name: "Marshall Islands" },
  //{ code: "MQ", name: "Martinique" },
  //{ code: "MR", name: "Mauritania" },
  //{ code: "MU", name: "Mauritius" },
  //{ code: "YT", name: "Mayotte" },
  { code: "MX", name: t("KYC_account_verification.mexico") },
  //{ code: "FM", name: "Micronesia, Federated States of" },
  //{ code: "MD", name: "Moldova, Republic of" },
  //{ code: "MC", name: "Monaco" },
  { code: "MN", name: t("KYC_account_verification.mongolia") },
  //{ code: "ME", name: "Montenegro" },
  //{ code: "MS", name: "Montserrat" },
  //{ code: "MA", name: "Morocco" },
  //{ code: "MZ", name: "Mozambique" },
  //{ code: "MM", name: "Myanmar" },
  //{ code: "NA", name: "Namibia" },
  //{ code: "NR", name: "Nauru" },
  //{ code: "NP", name: "Nepal" },
  { code: "NL", name: t("KYC_account_verification.netherlands") },
  //{ code: "NC", name: "New Caledonia" },
  { code: "NZ", name: t("KYC_account_verification.newzealand") },
  //{ code: "NI", name: "Nicaragua" },
  //{ code: "NE", name: "Niger" },
  //{ code: "NG", name: "Nigeria" },
  //{ code: "NU", name: "Niue" },
  //{ code: "NF", name: "Norfolk Island" },
  //{ code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: t("KYC_account_verification.norway") },
  //{ code: "OM", name: "Oman" },
  //{ code: "PK", name: "Pakistan" },
  //{ code: "PW", name: "Palau" },
  //{ code: "PS", name: "Palestine, State of" },
  //{ code: "PA", name: "Panama" },
  //{ code: "PG", name: "Papua New Guinea" },
  //{ code: "PY", name: "Paraguay" },
  //{ code: "PE", name: "Peru" },
  { code: "PH", name: t("KYC_account_verification.philippines") },
  //{ code: "PN", name: "Pitcairn" },
  { code: "PL", name: t("KYC_account_verification.poland") },
  { code: "PT", name: t("KYC_account_verification.portugal") },
  //{ code: "PR", name: "Puerto Rico" },
  { code: "QA", name: t("KYC_account_verification.qatar") },
  //{ code: "RE", name: "R\u00e9union" },
  //{ code: "RO", name: "Romania" },
  { code: "RU", name: t("KYC_account_verification.russia") },
  //{ code: "RW", name: "Rwanda" },
  //{ code: "BL", name: "Saint Barth\u00e9lemy" },
  //{ code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  //{ code: "KN", name: "Saint Kitts and Nevis" },
  //{ code: "LC", name: "Saint Lucia" },
  //{ code: "MF", name: "Saint Martin (French part)" },
  //{ code: "PM", name: "Saint Pierre and Miquelon" },
  //{ code: "VC", name: "Saint Vincent and the Grenadines" },
  //{ code: "WS", name: "Samoa" },
  //{ code: "SM", name: "San Marino" },
  //{ code: "ST", name: "Sao Tome and Principe" },
  //{ code: "SA", name: "Saudi Arabia" },
  //{ code: "SN", name: "Senegal" },
  //{ code: "RS", name: "Serbia" },
  //{ code: "SC", name: "Seychelles" },
  //{ code: "SL", name: "Sierra Leone" },
  { code: "SG", name: t("KYC_account_verification.singapore") },
  //{ code: "SX", name: "Sint Maarten (Dutch part)" },
  //{ code: "SK", name: "Slovakia" },
  //{ code: "SI", name: "Slovenia" },
  //{ code: "SB", name: "Solomon Islands" },
  //{ code: "SO", name: "Somalia" },
  //{ code: "ZA", name: "South Africa" },
  //{ code: "GS", name: "South Georgia and the South Sandwich Islands" },
  //{ code: "SS", name: "South Sudan" },
  { code: "ES", name: t("KYC_account_verification.spain") },
  //{ code: "LK", name: "Sri Lanka" },
  //{ code: "SD", name: "Sudan" },
  //{ code: "SR", name: "Suriname" },
  //{ code: "SJ", name: "Svalbard and Jan Mayen" },
  //{ code: "SZ", name: "Swaziland" },
  { code: "SE", name: t("KYC_account_verification.sweden") },
  { code: "CH", name: t("KYC_account_verification.switzerland") },
  //{ code: "SY", name: "Syrian Arab Republic" },
  { code: "TW", name: t("KYC_account_verification.taiwan") },
  //{ code: "TJ", name: "Tajikistan" },
  //{ code: "TZ", name: "Tanzania, United Republic of" },
  { code: "TH", name: t("KYC_account_verification.thailand") },
  //{ code: "TL", name: "Timor-Leste" },
  //{ code: "TG", name: "Togo" },
  //{ code: "TK", name: "Tokelau" },
  //{ code: "TO", name: "Tonga" },
  //{ code: "TT", name: "Trinidad and Tobago" },
  //{ code: "TN", name: "Tunisia" },
  //{ code: "TR", name: t("KYC_account_verification.turkey") },
  //{ code: "TM", name: "Turkmenistan" },
  //{ code: "TC", name: "Turks and Caicos Islands" },
  //{ code: "TV", name: "Tuvalu" },
  //{ code: "UG", name: "Uganda" },
  //{ code: "UA", name: "Ukraine" },
  //{ code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: t("KYC_account_verification.unitedkingdom") },
  { code: "US", name: t("KYC_account_verification.unitedstates") },
  //{ code: "UM", name: "United States Minor Outlying Islands" },
  //{ code: "UY", name: "Uruguay" },
  //{ code: "UZ", name: "Uzbekistan" },
  //{ code: "VU", name: "Vanuatu" },
  //{ code: "VE", name: "Venezuela, Bolivarian Republic of" },
  { code: "VN", name: t("KYC_account_verification.vietnam") },
  //{ code: "VG", name: "Virgin Islands, British" },
  //{ code: "VI", name: "Virgin Islands, U.S." },
  //{ code: "WF", name: "Wallis and Futuna" },
  //{ code: "EH", name: "Western Sahara" },
  //{ code: "YE", name: "Yemen" },
  //{ code: "ZM", name: "Zambia" },
  //{ code: "ZW", name: "Zimbabwe" }
];
